#!/bin/bash

export MONGO_URL="mongodb://localhost:27001/depthwatch?replicaSet=kyote&directConnection=true"
export MONGO_OPLOG_URL="mongodb://oplogger:PasswordForOplogger@localhost:27001/local?authSource=admin&replicaSet=kyote&directConnection=true"

export FORCE_SSL=1

export TOOL_NODE_FLAGS="--no-expose-gc --max-old-space-size=8192 --optimize_for_size --gc-interval=100" 


meteor run -p 3000 --exclude-archs web.browser.legacy
