#!/bin/bash

export MONGO_URL="mongodb://localhost:27001/depthwatch?replicaSet=coworkr&directConnection=true"
export MONGO_OPLOG_URL="mongodb://oplogger:PasswordForOplogger@localhost:27001/local?authSource=admin&replicaSet=coworkr&directConnection=true"

export FORCE_SSL=1

export TOOL_NODE_FLAGS="--no-expose-gc --max-old-space-size=8192 --optimize_for_size --gc-interval=100" 
export SERVER_NODE_OPTIONS="--no-expose-gc --max-old-space-size=8192 --optimize_for_size --gc-interval=100" 



WARN_WHEN_USING_OLD_API=true meteor run -p 3000 --exclude-archs web.browser.legacy
